### ISSUE TITLE
Cannot change model type on existing skin.

### ISSUE THREAD

**Issue by mineblock11** [mineblock11/SkinShuffle#4]
[Screencast from 19-06-23 18:34:56.webm](https://github.com/mineblock11/SkinShuffle/assets/93472213/26a3db6d-d116-4de2-ac9a-6150dcded369)

**Comment by enjarai** [comment]
As it currently works, you have to re-source the skin to update the model, so the button should probably be hidden if you have "keep current" selected.

I don't think its nessecary to be able to change the model seperately from the skin, since you'll almost always use the same model for a specific skin.

**Comment by mineblock11** [comment]
What if the user chose the wrong model though?

**Comment by enjarai** [comment]
They would notice that on the preview in theory, which would give them the change to change it easily before saving the preset.
